import { useState } from 'react';
import type { InstanceDetail } from '../../types/database';

interface CredentialsModalProps {
  instance: InstanceDetail;
  password: string;
  onClose: () => void;
}

const CredentialsModal = ({ instance, password, onClose }: CredentialsModalProps) => {
  const [copied, setCopied] = useState<string | null>(null);

  const copyToClipboard = (text: string, label: string) => {
    navigator.clipboard.writeText(text);
    setCopied(label);
    setTimeout(() => setCopied(null), 2000);
  };

  const handleDownloadPDF = () => {
    // TODO: When backend is ready, call endpoint: POST /api/instances/{id}/download-credentials
    // For now, create a simple text file
    const content = `
DATABASE CREDENTIALS - SAVE THIS INFORMATION
============================================

Instance Name: ${instance.name}
Database Engine: ${instance.engine.name}
Status: ${instance.status}

CONNECTION DETAILS:
------------------
Host: ${instance.credentials?.host}
Port: ${instance.credentials?.port}
Database: ${instance.credentials?.database}
Username: ${instance.credentials?.username}
Password: ${password}

Created: ${new Date(instance.createdAt).toLocaleString()}

⚠️ IMPORTANT: This password is shown only once. Keep it secure!

Generated by Nebula Cloud Database Platform
    `.trim();

    const blob = new Blob([content], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${instance.name}-credentials.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  return (
    <div className="fixed inset-0 bg-black/50 backdrop-blur-sm flex items-center justify-center z-50 p-4">
      <div className="bg-white rounded-2xl shadow-2xl max-w-2xl w-full max-h-[90vh] overflow-y-auto">
        <div className="p-8">
          {/* Warning Header */}
          <div className="bg-gradient-to-r from-red-500 to-orange-500 text-white rounded-lg p-6 mb-6">
            <div className="flex items-start gap-3">
              <svg className="w-8 h-8 flex-shrink-0 mt-1" fill="currentColor" viewBox="0 0 20 20">
                <path fillRule="evenodd" d="M8.257 3.099c.765-1.36 2.722-1.36 3.486 0l5.58 9.92c.75 1.334-.213 2.98-1.742 2.98H4.42c-1.53 0-2.493-1.646-1.743-2.98l5.58-9.92zM11 13a1 1 0 11-2 0 1 1 0 012 0zm-1-8a1 1 0 00-1 1v3a1 1 0 002 0V6a1 1 0 00-1-1z" clipRule="evenodd" />
              </svg>
              <div>
                <h3 className="text-xl font-bold mb-2">⚠️ Save These Credentials Now!</h3>
                <p className="text-white/90">
                  This is the <strong>only time</strong> you will see the password. 
                  Make sure to save it securely before closing this window.
                </p>
              </div>
            </div>
          </div>

          {/* Title */}
          <h2 className="text-3xl font-bold text-gray-900 mb-2">
            Instance Created Successfully! 
          </h2>
          <p className="text-gray-600 mb-6">
            Your <strong>{instance.engine.name}</strong> instance "{instance.name}" is ready to use.
          </p>

          {/* Credentials */}
          <div className="bg-gray-50 rounded-xl p-6 mb-6 border-2 border-purple-200">
            <h3 className="font-bold text-gray-900 mb-4 text-lg">Connection Details</h3>
            
            <div className="space-y-3">
              {/* Host */}
              <div className="flex items-center justify-between p-3 bg-white rounded-lg border border-gray-200">
                <div className="flex-1">
                  <div className="text-sm text-gray-600 mb-1">Host</div>
                  <div className="font-mono font-semibold text-gray-900">
                    {instance.credentials?.host}
                  </div>
                </div>
                <button
                  onClick={() => copyToClipboard(instance.credentials?.host || '', 'host')}
                  className="ml-3 px-3 py-2 bg-purple-100 text-purple-700 rounded-lg hover:bg-purple-200 transition-colors text-sm font-semibold"
                >
                  {copied === 'host' ? 'Copied!' : 'Copy'}
                </button>
              </div>

              {/* Port */}
              <div className="flex items-center justify-between p-3 bg-white rounded-lg border border-gray-200">
                <div className="flex-1">
                  <div className="text-sm text-gray-600 mb-1">Port</div>
                  <div className="font-mono font-semibold text-gray-900">
                    {instance.credentials?.port}
                  </div>
                </div>
                <button
                  onClick={() => copyToClipboard(instance.credentials?.port?.toString() || '', 'port')}
                  className="ml-3 px-3 py-2 bg-purple-100 text-purple-700 rounded-lg hover:bg-purple-200 transition-colors text-sm font-semibold"
                >
                  {copied === 'port' ? 'Copied!' : 'Copy'}
                </button>
              </div>

              {/* Database */}
              <div className="flex items-center justify-between p-3 bg-white rounded-lg border border-gray-200">
                <div className="flex-1">
                  <div className="text-sm text-gray-600 mb-1">Database</div>
                  <div className="font-mono font-semibold text-gray-900">
                    {instance.credentials?.database}
                  </div>
                </div>
                <button
                  onClick={() => copyToClipboard(instance.credentials?.database || '', 'database')}
                  className="ml-3 px-3 py-2 bg-purple-100 text-purple-700 rounded-lg hover:bg-purple-200 transition-colors text-sm font-semibold"
                >
                  {copied === 'database' ? 'Copied!' : 'Copy'}
                </button>
              </div>

              {/* Username */}
              <div className="flex items-center justify-between p-3 bg-white rounded-lg border border-gray-200">
                <div className="flex-1">
                  <div className="text-sm text-gray-600 mb-1">Username</div>
                  <div className="font-mono font-semibold text-gray-900">
                    {instance.credentials?.username}
                  </div>
                </div>
                <button
                  onClick={() => copyToClipboard(instance.credentials?.username || '', 'username')}
                  className="ml-3 px-3 py-2 bg-purple-100 text-purple-700 rounded-lg hover:bg-purple-200 transition-colors text-sm font-semibold"
                >
                  {copied === 'username' ? 'Copied!' : 'Copy'}
                </button>
              </div>

              {/* Password - Highlighted */}
              <div className="flex items-center justify-between p-3 bg-gradient-to-r from-red-50 to-orange-50 rounded-lg border-2 border-red-300">
                <div className="flex-1">
                  <div className="text-sm text-red-700 mb-1 font-semibold flex items-center gap-2">
                    <svg className="w-4 h-4" fill="currentColor" viewBox="0 0 20 20">
                      <path fillRule="evenodd" d="M5 9V7a5 5 0 0110 0v2a2 2 0 012 2v5a2 2 0 01-2 2H5a2 2 0 01-2-2v-5a2 2 0 012-2zm8-2v2H7V7a3 3 0 016 0z" clipRule="evenodd" />
                    </svg>
                    Password (shown only once!)
                  </div>
                  <div className="font-mono font-bold text-gray-900 text-lg break-all">
                    {password}
                  </div>
                </div>
                <button
                  onClick={() => copyToClipboard(password, 'password')}
                  className="ml-3 px-3 py-2 bg-red-500 text-white rounded-lg hover:bg-red-600 transition-colors text-sm font-semibold"
                >
                  {copied === 'password' ? 'Copied!' : 'Copy'}
                </button>
              </div>
            </div>
          </div>

          {/* Actions */}
          <div className="flex gap-3">
            <button
              onClick={handleDownloadPDF}
              className="flex-1 px-6 py-3 bg-gray-100 text-gray-900 rounded-lg font-semibold hover:bg-gray-200 transition-colors flex items-center justify-center gap-2"
            >
              <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 10v6m0 0l-3-3m3 3l3-3m2 8H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
              </svg>
              Download as Text File
            </button>
            <button
              onClick={onClose}
              className="flex-1 px-6 py-3 bg-gradient-to-r from-purple-600 to-blue-600 text-white rounded-lg font-semibold hover:from-purple-700 hover:to-blue-700 transition-all shadow-lg"
            >
              I've Saved My Credentials
            </button>
          </div>

          {/* Footer Note */}
          <p className="text-center text-sm text-gray-500 mt-4">
            You can rotate the password later from the instance management page
          </p>
        </div>
      </div>
    </div>
  );
};

export default CredentialsModal;
