import { useState } from 'react';
import jsPDF from 'jspdf';
import type { CreateInstanceResponse } from '../../types/database';

interface CredentialsModalProps {
  instance: CreateInstanceResponse;
  password: string;
  onClose: () => void;
}

const CredentialsModal = ({ instance, password, onClose }: CredentialsModalProps) => {
  const [copied, setCopied] = useState<string | null>(null);

  const copyToClipboard = (text: string, label: string) => {
    navigator.clipboard.writeText(text);
    setCopied(label);
    setTimeout(() => setCopied(null), 2000);
  };

  const handleDownloadPDF = () => {
    const doc = new jsPDF();
    
    // Title
    doc.setFontSize(20);
    doc.setFont('helvetica', 'bold');
    doc.text('DATABASE CREDENTIALS', 105, 20, { align: 'center' });
    
    doc.setFontSize(12);
    doc.setFont('helvetica', 'normal');
    doc.text('SAVE THIS INFORMATION', 105, 28, { align: 'center' });
    
    // Warning box
    doc.setFillColor(255, 200, 200);
    doc.rect(15, 35, 180, 15, 'F');
    doc.setFontSize(10);
    doc.setFont('helvetica', 'bold');
    doc.text('IMPORTANT: Keep these credentials secure!', 20, 44);
    
    // Instance details
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(14);
    doc.text('Instance Information', 20, 60);
    
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(11);
    let y = 70;
    
    doc.setFont('helvetica', 'bold');
    doc.text('Database Name:', 20, y);
    doc.setFont('helvetica', 'normal');
    doc.text(instance.databaseName, 70, y);
    
    y += 10;
    doc.setFont('helvetica', 'bold');
    doc.text('Database Engine:', 20, y);
    doc.setFont('helvetica', 'normal');
    doc.text(instance.engineName, 70, y);
    
    y += 10;
    doc.setFont('helvetica', 'bold');
    doc.text('Status:', 20, y);
    doc.setFont('helvetica', 'normal');
    doc.text(instance.status, 70, y);
    
    // Connection Details
    y += 20;
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(14);
    doc.text('Connection Details', 20, y);
    
    y += 10;
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(11);
    
    doc.setFont('helvetica', 'bold');
    doc.text('Host:', 20, y);
    doc.setFont('helvetica', 'normal');
    doc.text(instance.containerIp, 70, y);
    
    y += 10;
    doc.setFont('helvetica', 'bold');
    doc.text('Port:', 20, y);
    doc.setFont('helvetica', 'normal');
    doc.text(instance.containerPort.toString(), 70, y);
    
    y += 10;
    doc.setFont('helvetica', 'bold');
    doc.text('Database:', 20, y);
    doc.setFont('helvetica', 'normal');
    doc.text(instance.databaseName, 70, y);
    
    y += 10;
    doc.setFont('helvetica', 'bold');
    doc.text('Username:', 20, y);
    doc.setFont('helvetica', 'normal');
    doc.text(instance.dbUsername, 70, y);
    
    y += 10;
    doc.setFont('helvetica', 'bold');
    doc.text('Password:', 20, y);
    doc.setFont('helvetica', 'normal');
    doc.text(password, 70, y);
    
    // Footer
    y += 20;
    doc.setFontSize(9);
    doc.setTextColor(128, 128, 128);
    doc.text(`Created: ${new Date(instance.createdAt).toLocaleString()}`, 20, y);
    
    y += 10;
    doc.text('Generated by Nebula Cloud Database Platform', 105, y, { align: 'center' });
    
    // Save the PDF
    doc.save(`${instance.databaseName}-credentials.pdf`);
  };

  return (
    <div className="fixed inset-0 bg-black/50 backdrop-blur-sm flex items-center justify-center z-50 p-4">
      <div className="bg-gray-900 rounded-2xl shadow-2xl max-w-2xl w-full max-h-[90vh] overflow-y-auto border border-purple-500/30">
        <div className="p-8">
          {/* Warning Header */}
          <div className="bg-gradient-to-r from-red-500 to-orange-500 text-white rounded-lg p-6 mb-6">
            <div className="flex items-start gap-3">
              <svg className="w-8 h-8 flex-shrink-0 mt-1" fill="currentColor" viewBox="0 0 20 20">
                <path fillRule="evenodd" d="M8.257 3.099c.765-1.36 2.722-1.36 3.486 0l5.58 9.92c.75 1.334-.213 2.98-1.742 2.98H4.42c-1.53 0-2.493-1.646-1.743-2.98l5.58-9.92zM11 13a1 1 0 11-2 0 1 1 0 012 0zm-1-8a1 1 0 00-1 1v3a1 1 0 002 0V6a1 1 0 00-1-1z" clipRule="evenodd" />
              </svg>
              <div>
                <h3 className="text-xl font-bold mb-2">⚠️ Important Information</h3>
                <p className="text-white/90">
                  Save your database credentials securely. You can check your email for detailed connection information.
                </p>
              </div>
            </div>
          </div>

          {/* Title */}
          <h2 className="text-3xl font-bold bg-gradient-to-r from-purple-400 to-blue-400 bg-clip-text text-transparent mb-2">
            Instance Created Successfully! 
          </h2>
          <p className="text-gray-300 mb-6">
            Your <strong className="text-purple-400">{instance.engineName}</strong> database "{instance.databaseName}" is ready to use.
          </p>

          {/* Credentials */}
          <div className="bg-gray-800/50 rounded-xl p-6 mb-6 border-2 border-purple-500/30">
            <h3 className="font-bold text-white mb-4 text-lg">Connection Details</h3>
            
            <div className="space-y-3">
              {/* Host */}
              <div className="flex items-center justify-between p-3 bg-gray-700/50 rounded-lg border border-gray-600">
                <div className="flex-1">
                  <div className="text-sm text-gray-400 mb-1">Host</div>
                  <div className="font-mono font-semibold text-gray-100">
                    {instance.containerIp}
                  </div>
                </div>
                <button
                  onClick={() => copyToClipboard(instance.containerIp || '', 'host')}
                  className="ml-3 px-3 py-2 bg-purple-600 text-white rounded-lg hover:bg-purple-700 transition-colors text-sm font-semibold"
                >
                  {copied === 'host' ? 'Copied!' : 'Copy'}
                </button>
              </div>

              {/* Port */}
              <div className="flex items-center justify-between p-3 bg-gray-700/50 rounded-lg border border-gray-600">
                <div className="flex-1">
                  <div className="text-sm text-gray-400 mb-1">Port</div>
                  <div className="font-mono font-semibold text-gray-100">
                    {instance.containerPort}
                  </div>
                </div>
                <button
                  onClick={() => copyToClipboard(instance.containerPort?.toString() || '', 'port')}
                  className="ml-3 px-3 py-2 bg-purple-600 text-white rounded-lg hover:bg-purple-700 transition-colors text-sm font-semibold"
                >
                  {copied === 'port' ? 'Copied!' : 'Copy'}
                </button>
              </div>

              {/* Database Name */}
              <div className="flex items-center justify-between p-3 bg-gray-700/50 rounded-lg border border-gray-600">
                <div className="flex-1">
                  <div className="text-sm text-gray-400 mb-1">Database</div>
                  <div className="font-mono font-semibold text-gray-100">
                    {instance.databaseName}
                  </div>
                </div>
                <button
                  onClick={() => copyToClipboard(instance.databaseName || '', 'database')}
                  className="ml-3 px-3 py-2 bg-purple-600 text-white rounded-lg hover:bg-purple-700 transition-colors text-sm font-semibold"
                >
                  {copied === 'database' ? 'Copied!' : 'Copy'}
                </button>
              </div>

              {/* Username */}
              <div className="flex items-center justify-between p-3 bg-gray-700/50 rounded-lg border border-gray-600">
                <div className="flex-1">
                  <div className="text-sm text-gray-400 mb-1">Username</div>
                  <div className="font-mono font-semibold text-gray-100">
                    {instance.dbUsername}
                  </div>
                </div>
                <button
                  onClick={() => copyToClipboard(instance.dbUsername || '', 'username')}
                  className="ml-3 px-3 py-2 bg-purple-600 text-white rounded-lg hover:bg-purple-700 transition-colors text-sm font-semibold"
                >
                  {copied === 'username' ? 'Copied!' : 'Copy'}
                </button>
              </div>

              {/* Password - Highlighted */}
              <div className="flex items-center justify-between p-3 bg-gradient-to-r from-red-900/50 to-orange-900/50 rounded-lg border-2 border-red-500/50">
                <div className="flex-1">
                  <div className="text-sm text-red-400 mb-1 font-semibold flex items-center gap-2">
                    <svg className="w-4 h-4" fill="currentColor" viewBox="0 0 20 20">
                      <path fillRule="evenodd" d="M5 9V7a5 5 0 0110 0v2a2 2 0 012 2v5a2 2 0 01-2 2H5a2 2 0 01-2-2v-5a2 2 0 012-2zm8-2v2H7V7a3 3 0 016 0z" clipRule="evenodd" />
                    </svg>
                    Password
                  </div>
                  <div className="font-mono font-bold text-gray-100 text-lg break-all">
                    {password}
                  </div>
                </div>
                <button
                  onClick={() => copyToClipboard(password, 'password')}
                  className="ml-3 px-3 py-2 bg-red-600 text-white rounded-lg hover:bg-red-700 transition-colors text-sm font-semibold"
                >
                  {copied === 'password' ? 'Copied!' : 'Copy'}
                </button>
              </div>
            </div>
          </div>

          {/* Actions */}
          <div className="flex gap-3">
            <button
              onClick={handleDownloadPDF}
              className="flex-1 px-6 py-3 bg-gray-700 text-white rounded-lg font-semibold hover:bg-gray-600 transition-colors flex items-center justify-center gap-2"
            >
              <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 10v6m0 0l-3-3m3 3l3-3m2 8H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
              </svg>
              Download as PDF
            </button>
            <button
              onClick={onClose}
              className="flex-1 px-6 py-3 bg-gradient-to-r from-purple-600 to-blue-600 text-white rounded-lg font-semibold hover:from-purple-700 hover:to-blue-700 transition-all shadow-lg"
            >
              I've Saved My Credentials
            </button>
          </div>

          {/* Footer Note */}
          <p className="text-center text-sm text-gray-400 mt-4">
            Check your email for complete connection details and credentials
          </p>
        </div>
      </div>
    </div>
  );
};

export default CredentialsModal;
